### ISSUE TITLE
How to make promise from web socket API?

### ISSUE THREAD

**Issue by allawitte** [traviskaufman/co-talk-examples#1]
I have an API for nodejs for some external server.
Something like that:
Marker = require('node-market')
myMarket = new Market();
myMarket.websockets.trades(request[1], (trades, error) => {
                if (error) {
                   send to external client program by TCP(error);
                }
                else {
                    send to external client program by TCP(trades);
                });

The API are originally made as callback in web socket. Is it possible to redo it as promise?

**Comment by traviskaufman** [comment]
Hi!

So first off, this talk is a bit outdated. If you're looking for a good way to handle asynchronicity in the same way you would with coroutines, I'd recommend looking at [async/await](https://javascript.info/async-await)

That being said, for your use-case above it looks like you're processing a _stream_ of data, in which case I think a library like [RxJS](https://github.com/ReactiveX/rxjs) might be useful to you. Check out https://hackernoon.com/a-semi-quick-guide-to-reliable-stream-processing-with-rxjs-77cd8cb47f38 which talks about this :) Hope that helps!
